### PR TITLE
midterm checkpoint pull request

### PR DESCRIPTION
**Pull request by yahyalrq**

### CODE REVIEW

**Review by dsanmart — APPROVED** [review]
lgtm

**Review by miguelgfierro — COMMENTED** [review]
The usual way for several people to work together in the same branch would be via PRs. For example, if @pabloortegaa started a branch to add the data, now instead of a different person committing to the same branch, you would do a PR to Pablo's branch. If Pablo is ok with the code, he would merge the code into his branch, and will ask the rest of the team to review before emerging to main.

Makes sense?

**Comment by yahyalrq** [comment]
Yeah makes sense. Thanks

**Review by miguelgfierro — COMMENTED** [review]
There is a big PR with all the code. This is difficult to review and it is not clear to understand who did what. Going forward, it would be great if each new feature added to the codebase has a different branch and one owner. When the code is ready, the person would do a PR to main, and the rest of the team would review.

**Pull request merged**
